### ISSUE TITLE
🌕 complete `scipy.interpolate`

### ISSUE THREAD

**Issue by jorenham** [jorenham/scipy-stubs#101]
it uses `Untyped*` ~489~ ~465~ ~376~ ~297~ ~289~ ~221~ ~189~ ~160~ ~128~ ~65~ 43 times

- [x] `dfitpack`
- [x] `fitpack2`
- [x] `fitpack`
- [x] `interpnd`
- [x] `interpolate`
- [x] `ndgriddata`
- [x] `polyint`
- [x] `rbf`
- [x] `_bsplines`
- [x] `_cubic`
- [x] `_fitpack2`
- [x] `_fitpack_impl`
- [x] `_fitpack_py`
- [x] `_interpolate`
- [x] `_ndbspline`
- [x] `_ndgriddata`
- [x] `_pade`
- [x] `_polyint`
- [x] `_rbfinterp`
- [x] `_rbfinterp_pythran`
- [x] `_rbf`
- [x] `_rgi`

**Comment by berhoel** [comment]
The signature for "interpolate._cubic.CubicSpline" is wrong. Argument ``bc_type`` should be
  bc_type:  Literal["not-a-knot","periodic","clamped","natural"]|tuple[tuple[int,float|ArrayLike]|Literal["not-a-knot","clamped","natural"],tuple[int,float|ArrayLike]|Literal["not-a-knot","clamped","natural"]] = "not-a-knot"

**Comment by jorenham** [comment]
> The signature for "interpolate._cubic.CubicSpline" is wrong. Argument `bc_type` should be bc_type: Literal["not-a-knot","periodic","clamped","natural"]|tuple[tuple[int,float|ArrayLike]|Literal["not-a-knot","clamped","natural"],tuple[int,float|ArrayLike]|Literal["not-a-knot","clamped","natural"]] = "not-a-knot"

Rhanks for the reporting this, @berhoel. I have fixed it in #182.
