### ISSUE TITLE
🤖 codemod for missing `__all__`

### ISSUE THREAD

**Issue by jorenham** [jorenham/scipy-stubs#127]
Module stubs without `__all__` aren't reported by stubtest:
Write a codemod that copies the missing `__all__` from a `{}.py` to its `{}.pyi` if needed.

**Comment by Avasam** [comment]
You might be interested in https://github.com/python/mypy/pull/18005

**Comment by jorenham** [comment]
> You might be interested in [python/mypy#18005](https://github.com/python/mypy/pull/18005)

Yea that seems like good news!

This codemod would go a step further than that:
It would automatically copy over the `__all__` if they are missing. In our case, I wouldn't be surprised if that would affect >100 modules.

**Comment by jorenham** [comment]
At this point there shouldn't be many such cases left actually. So I'm closing this as it'll be enforced by https://github.com/python/mypy/pull/18005 in the upcoming (based)mypy release.
