### ISSUE TITLE
migrate from `poetry` to `uv`

### ISSUE THREAD

**Issue by jorenham** [jorenham/scipy-stubs#49]
[poe doesn't require `poetry`](https://poethepoet.natn.io/guides/without_poetry.html), so there's no need to migrate the current `poe` commands ([but we probably will](https://github.com/jorenham/scipy-stubs/issues/216)).

**Comment by jorenham** [comment]
I wasn't able to get `uv` working, which I'm guessing is because either `uv` or hatchling don't support stub-only packages yet (something to do with the `-stub` suffix) 🤷🏻

**Comment by pavyamsiri** [comment]
What is the goal of this issue? I have been using uv recently so I am interested.

**Comment by jorenham** [comment]
Migrate from poetry to uv. 

See the linked branch for my (failed) attempt
